# fly.toml app configuration file generated for tour-of-heross on 2023-11-03T11:44:20-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tour-of-heross"
primary_region = "gru"
console_command = "/rails/bin/rails console"

[build]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
